### ISSUE TITLE
Var(Value at Risk) data

### ISSUE THREAD

**Issue by Tkp0056** [RuchiTanmay/nselib#31]
Can we get Var data or I need to build and push it here ?

**Comment by RuchiTanmay** [comment]
Hi, Can you please explain your requirements, I can help you.

Tanmay,
Tanmay

**Comment by neha0056** [comment]
![image](https://github.com/user-attachments/assets/7b797997-91e9-4847-af73-47ba8269e7c9)
There is one file in "CM - Var Margin Rates (End of the Day)
Is it possible to get it from your code or do you have idea how can I do it ?
It will be really helpful for our community, since we don't need to do it manually.

**Comment by RuchiTanmay** [comment]
I will add these data in next version. 
Can you contact me on my WP 8895885474.
Just want to know how it Var data is so relevant.

**Comment by RuchiTanmay** [comment]
this data is available now in nselib 1.1
